In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1,2])


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [3]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [4]:
array_example.ndim

3

In [5]:
array_example.size

24

In [6]:
array_example.shape

(3, 2, 4)

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = np.arange(6)
print(arr)
b = arr.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [11]:
arr = np.array([0,1, 2, 3, 4, 5, 6, 7 ])
b = arr.reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [13]:
arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 11, 13])
arr.shape
print(arr.shape)

(10,)


In [15]:
arr2 = arr[np.newaxis]
print(arr2.shape)
print(arr2)

(1, 10)
[[ 0  1  2  3  4  5  6  7 11 13]]


In [16]:
row_vector = arr[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 10)
[[ 0  1  2  3  4  5  6  7 11 13]]


In [17]:
col_vector = arr[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(10, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [11]
 [13]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.shape


(6,)

In [19]:
b = np.expand_dims(arr, axis=1)
b.shape

(6, 1)

In [20]:
b = np.expand_dims(arr, axis=0)
b.shape

(1, 6)

In [21]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [28]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
print(arr[arr>=5])

[ 5  6  7  8  9 10 11 12]


In [32]:
divisible_by_2 = arr[arr%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [33]:
divisible_by_2 = arr[arr%3==2]

print(divisible_by_2)

[ 2  5  8 11]


In [34]:
c = arr[(arr > 2) & (arr < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [35]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [39]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [40]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [41]:
np.hsplit(arrsplit,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
a.sum(axis=0)
a.sum(axis=1)

array([10, 26, 42])

In [53]:
a*a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [54]:
a/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [57]:
a.sum()

78

In [58]:
a.min()

1

In [59]:
a.max()

12

In [60]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [67]:
np.ones((3,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
np.random.random((3,2))

array([[0.11419716, 0.94469456],
       [0.66617342, 0.91218655],
       [0.25725194, 0.15098121]])

In [70]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [71]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [72]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [73]:
print(data*2)

[[2 4]
 [6 8]]


In [74]:
print(data/2)

[[0.5 1. ]
 [1.5 2. ]]


In [75]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [76]:
data_col = np.array([[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12]]).T
print(data_col)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
